# @package _group_

agent_type: "DDPG"

hyper_params:
  gamma: 0.99
  tau: 0.005
  buffer_size: 10000
  batch_size: 64
  initial_random_action: 5000 #10000
  multiple_update: 1
  gradient_clip_ac: 0.5
  gradient_clip_cr: 1.0

learner_cfg:
  backbone:
    actor:
    critic:
  head:
    actor:
      type: "MLP"
      configs:
        hidden_sizes: [256, 256]
        output_activation: "tanh"
    critic:
      type: "MLP"
      configs:
        hidden_sizes: [256, 256]
        output_size: 1
        output_activation: "identity"
  optim_cfg:
    lr_actor: 0.0003
    lr_critic: 0.0003
    weight_decay: 0.000001

  noise_cfg:
    ou_noise_theta: 0.0
    ou_noise_sigma: 0.0