# @package _group_

agent_type: "DQN"

hyper_params:
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000         # openai baselines: 10000
  batch_size: 32               # openai baselines: 32
  update_starts_from: 500000  # openai baselines: 10000
  multiple_update: 1          # multiple learning updates
  train_freq: 15               # in openai baselines, train_freq = 4
  gradient_clip: 10         # dueling: 10.0
  n_step: 3
  w_n_step: 1.0
  w_q_reg: 0.0000001
  per_alpha: 0.6              # openai baselines: 0.6
  per_beta: 0.4
  per_eps: 0.000001
  max_epsilon: 1.0
  min_epsilon: 0.01           # openai baselines: 0.01
  epsilon_decay: 0.00001      # openai baselines: 1e-7 / 1e-1

learner_cfg:
  backbone:
    #type: "CNN"
    #configs: 
      #input_sizes: [4, 32, 64]
      #output_sizes: [32, 64, 64]
      #kernel_sizes: [1, 1, 1]
      #stride_sizes: [4, 2, 1]
      #kernel_sizes: [8, 4, 3]
      #stride_sizes: [4, 2, 1]
  head: 
    type: "MLP"
    configs:
      hidden_sizes: [128, 64]
      v_min: -300
      v_max: 300
      atom_size: 1530
      output_activation: "identity"
      use_noisy_net: True
      use_recurrency_layer: True
  optim_cfg:
    lr_dqn: 0.0001
    weight_decay: 0.0000001
    adam_eps: 0.00000001
