project_name: "GYMLOB"
experiment_name: "DDPG_TRAIN"

seeds: [5422608]
log_cmd: False
log_wb: True
save_params_every: 100 # in episodes
num_experiments_in_parallel: 1
test: False

num_train_episodes: 20000
max_episode_steps: 120

# data config
orderbook_file_path: "/efs/mm/lobrep/data/TSLA_2015-01-01_2015-01-31_10/TSLA_2015-01-02_34200000_57600000_orderbook_10.csv"
#orderbook_file_path: "/Users/mahmoud/_code/_air/lobmod/data/TSLA_2015-01-01_2015-01-31_10/TSLA_2015-01-02_34200000_57600000_orderbook_10.csv"

orders_file_path: "/efs/mm/lobrep/data/TSLA_2015-01-01_2015-01-31_10/TSLA_2015-01-05_34200000_57600000_message_10.csv"
#orders_file_path: "/Users/mahmoud/_code/_air/lobmod/data/TSLA_2015-01-01_2015-01-31_10/TSLA_2015-01-05_34200000_57600000_message_10.csv"

# client order information
instrument: "TSLA"
date: "2015-01-02"
frequency: "1s"
direction: "BUY"
quantity: 1000
duration: 120
benchmark: "arrival"

defaults:
  - algo: ddpg